#!/bin/bash

set -e

chown -R cif:cif /var/lib/fm
chown -R cif:cif /etc/cif

export CSIRTG_FM_CACHE_PATH="/var/lib/fm"
export CSIRTG_FM_RUNTIME_PATH="/var/lib/fm"
export CSIRTG_FM_GOBACK_DAYS=21

if [ -z ${CIF_REMOTE} ] || [ ${CIF_REMOTE} == "" ]; then
    export CIF_REMOTE="ipc:///var/lib/cif/router.ipc"
fi

if [ ! -d /local_rules ]; then
  mkdir /local_rules
fi

csirtg-fm --service -r /local_rules,/etc/cif/rules --remember --skip-invalid --client cifzmq --limit 10000
